In [26]:
import numpy as np 
np.zeros(3) # array([0., 0., 0.])

array([0., 0., 0.])

In [27]:
n =4 

x = np.zeros (n)
i =2 
x[i] =1 
print(x)

# array([0., 0., 1., 0.])  

[0. 0. 1. 0.]


In [28]:
np.ones(3) 

array([1., 1., 1.])

In [29]:
np.random.random(2)

array([0.52679286, 0.45251015])

In [30]:

x =np.array([1,2,3])
y= np.array([100,200 ,300])
print ('sum of arrays:', x+y)
print("diff of the arrays", x-y ) 

sum of arrays: [101 202 303]
diff of the arrays [ -99 -198 -297]


In [31]:
x= np.array ([1,2,3])
print (2.2*x)

[2.2 4.4 6.6]


In [32]:
x= np.array ([1,2,3])
print (x/2.2)   # // ==>  decimal 

[0.45454545 0.90909091 1.36363636]


In [33]:
x =5/2 
y=5//2 
print(x)
print(y)

2.5
2


In [ ]:
x= np.array ([1,2,3]) 
print (x+2)


In [ ]:
#linear comb 
a=np.array([1,2])
b =np.array([3,4])
alpha =-0.5
beta  =1.5 
c= alpha*a +beta*b 
print (c)


In [ ]:
#lhs#rhs 

In [ ]:
x =np.array([-1,2,2]) #inner 
y=np.array([1,0,-3])
print (np.inner(x,y))  

In [ ]:
#or use @ 

In [ ]:
import time 
a = np.random.random(10**5)
b = np.random.random(10**5)